import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  
    {
      path: '/dashboard/main',
      title: 'Dashboard',
      moduleName: 'dashboard',
      iconType: 'feather',
      icon: 'trello',
      class: '',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      submenu: [],
    },

    {
      path: 'profile',
      title: 'Profile',
      moduleName: 'profile',
      iconType: 'feather',
      icon: 'user',
      class: '',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      submenu: [],
    },

    {
        path: 'connectentry',
        title: 'Connect Entry',
        moduleName: 'connectentry',
        iconType: 'feather',
        icon: 'file-text',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'gnoteentry',
        title: 'GNote Entry',
        moduleName: 'gnoteentry',
        iconType: 'feather',
        icon: 'copy',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }, 
      {
        path: 'showcase',
        title: 'ShowCase',
        moduleName: 'showcase',
        iconType: 'feather',
        icon: 'server',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }, 
      {
        path: 'guestreg',
        title: 'Guest Registration',
        moduleName: 'guestreg',
        iconType: 'feather',
        icon: 'users',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }, 

      {
        path: 'jcomtables',
        title: 'JCOM Tables',
        moduleName: 'jcomtables',
        iconType: 'feather',
        icon: 'columns',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'searchmembers',
        title: 'Search Members',
        moduleName: 'searchmembers',
        iconType: 'feather',
        icon: 'search',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      
  // {
  // {
  //   path: 'Customer',
  //   title: 'Customer',
  //   moduleName: 'Customer',
  //   iconType: 'feather',
  //   icon: 'copy',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  // {
  //   path: 'User',
  //   title: 'User',
  //   moduleName: 'User',
  //   iconType: 'feather',
  //   icon: 'trello',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
 
  
  // {
  //   path: '',
  //   title: '-- Pages',
  //   moduleName: '',
  //   iconType: '',
  //   icon: '',
  //   class: '',
  //   groupTitle: true,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },



  
  


];
